name: Deployment

on:
  - push:
      tags:
        - "20.*"
        - "21.*"
        - "22.*"
        - "23.*"
        - "24.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build
    - name: Update extension’s meta
      run: |
        export VER=$(echo "$GITHUB_REF" | sed -e 's/refs\/tags\///')
        echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > dist/SOURCE_URL
        npm run version -- $VER
        cat dist/manifest.json
    - uses: actions/upload-artifact@40fe781 # TODO: update when v2 leaves beta
      with:
        path: dist

  deploy-to-chrome:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@3bdf740 # TODO: update when v2 leaves beta
    - run: cd artifact && npx chrome-webstore-upload-cli@1 upload --auto-publish
      env:
        EXTENSION_ID: kgilejfahkjidpaclkepbdoeioeohfmj
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  deploy-to-firefox:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@3bdf740 # TODO: update when v2 leaves beta
    - run: du -a
    - run: cd artifact && npx web-ext-submit@4
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
